# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AI Center at Dongguk University
email: jihie.kim@dgu.edu
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aic-dgu.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: 동국대학교 고등지능연구원 인공지능 연구실
address_line: 서울특별시 중구 필동로 1길 30 동국대학교 신공학관 2층 2163호 고등지능연구원 인공지능 연구실
company_email: jihie.kim@dgu.edu
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3162.8646334990954!2d126.99800091505267!3d37.55825293236063!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca302d491f811%3A0x809ffb62a47609b5!2sDongguk%20University%20Seoul%20Campus!5e0!3m2!1sen!2sus!4v1591172070134!5m2!1sen!2sus

# Social Link
facebook_link: https://www.facebook.com/DonggukAI/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
